name: Build Landscape from LFX

on:
  workflow_dispatch:
  schedule:
  - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jmertic/lfx-landscape-tools@main
        env:
          token: ${{ secrets.PAT }}
          ghid_token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - uses: jmertic/lfx-landscape-tools@main
        with:
          configfile: config-lfess.yml
          logfile: debug-lfess.yml
        env:
          token: ${{ secrets.PAT }}
          ghid_token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
